import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import prettier from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';

export default [
	{
		files: ['**/*.ts'],
		languageOptions: {
			parser: tsParser,
			sourceType: 'module',
		},
		plugins: {
			'@typescript-eslint': tsPlugin,
			prettier,
		},
		rules: {
			...tsPlugin.configs.recommended.rules,
			'prettier/prettier': 'error',
			'no-new-object': 'warn',
			'prefer-const': 'warn',
			'no-const-assign': 'warn',
			'no-var': 'warn',
			'object-shorthand': ['warn', 'properties'],
			'no-array-constructor': 'warn',
			'array-callback-return': 'warn',
			'no-eval': 'error',
			'no-useless-escape': 'warn',
			'wrap-iife': 'warn',
			'default-param-last': 'warn',
			'no-new-func': 'warn',
			'space-before-function-paren': 'warn',
			'space-before-blocks': 'warn',
			'no-param-reassign': 'warn',
			'function-paren-newline': 'warn',
			'prefer-arrow-callback': 'warn',
			'arrow-spacing': 'warn',
			'arrow-parens': 'warn',
			'arrow-body-style': 'warn',
			'no-confusing-arrow': 'warn',
			'no-useless-constructor': 'warn',
			'no-dupe-class-members': 'warn',
			'class-methods-use-this': 'error',
			'no-duplicate-imports': 'warn',
			'object-curly-newline': 'warn',
			'generator-star-spacing': ['warn', 'after'],
			'one-var': ['warn', 'never'],
			'operator-linebreak': ['warn', 'before'],
			'no-unneeded-ternary': 'warn',
			'no-mixed-operators': 'warn',
			'nonblock-statement-body-position': ['warn', 'below'],
			'brace-style': 'warn',
			'no-else-return': 'warn',
			'spaced-comment': 'warn',
			'space-infix-ops': 'warn',
			'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 2 }],
			'no-new-wrappers': 'warn',
			radix: 'warn',
			'id-length': 'warn',
			camelcase: 'warn',
			'no-underscore-dangle': 'warn',
			'no-console': 'warn',
			'no-empty': 'warn',
			'no-script-url': 'error',
			'no-with': 'error',
			'require-await': 'warn',
			'@typescript-eslint/explicit-function-return-type': 'warn',
			'@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
			'max-params': ['error', 3],
			'@typescript-eslint/no-duplicate-enum-values': 'warn',
			'no-empty-function': 'warn',
			'@typescript-eslint/no-empty-interface': 'warn',
		},
	},
	prettierConfig,
];
